# Generated by Django 4.0.7 on 2023-05-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0004_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
