# Generated by Django 4.0.7 on 2023-05-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0007_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
