# Generated by Django 4.0.7 on 2023-05-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0013_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
