# Generated by Django 4.0.7 on 2023-05-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0017_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
