# Generated by Django 4.0.7 on 2023-06-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0026_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='parent_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pharmapp.subcategory'),
        ),
    ]
