# Generated by Django 4.0.7 on 2023-06-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0031_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
