# Generated by Django 4.0.7 on 2023-06-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0042_alter_subcategory_parent_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_subcategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
